repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-yaml # Check YAML files for syntax errors only
    args: [--unsafe, --allow-multiple-documents]
  - id: no-commit-to-branch # Prevent committing to main / master
  - id: check-added-large-files
    exclude: |
      (?x)(
        .*uv.lock|
        .*pylock.toml
      )
  - id: check-merge-conflict # Check for files that contain merge conflict
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.2
  hooks:
  - id: ruff # better black/flake/isort
    files: ^backend/
    args:
    - --select
    - I # isorting
    - --fix
    - --exit-non-zero-on-fix
  - id: ruff-format
    files: ^backend/
ci:
  autoupdate_schedule: monthly
  autoupdate_commit_msg: "chore(deps): pre-commit.ci autoupdate"
