[build-system]
build-backend = "setuptools.build_meta"

requires = [ "setuptools>=80", "setuptools-scm[toml]>=6.2" ]

[project]
name = "fiab-core"
description = "Weather Forecast in a Box, core schemata and definitions"
readme = "README.md"
license = "Apache-2.0"
license-files = [ "LICENSE" ]
authors = [
  { name = "European Centre for Medium-Range Weather Forecasts (ECMWF)", email = "software.support@ecmwf.int" },
]
requires-python = ">=3.11"

dynamic = [ "version" ]

dependencies = [
    "pydantic",
    "earthkit-workflows", # NOTE technically we would need just cascade.low.core and some fluent.core, not the whole runtime -- possibly split down there as well
    "qubed>=0.3.0",
]

[dependency-groups]
dev = [
  "pytest>=8.4.2",
  "pytest-xdist>=3.8.0",
  "ty==0.0.2",
]

[tool.setuptools_scm]
version_file = "src/fiab_core/_version.py"
write_to_template = '''# Do not change! Do not track in version control!
__version__ = "{version}"
'''
local_scheme = "no-local-version"
root = ".."
fallback_version = "0.0.0"
tag_regex = '^[vd](?P<version>\d+(?:\.\d+){0,2}[^\+]*)(?:\+.*)?$'

[tool.ruff]
line-length = 140

lint.ignore = [ "E731" ]

[tool.uv.sources]
earthkit-workflows = { git = "https://github.com/ecmwf/earthkit-workflows", rev = "feat/expand-as-qubed" }
