[build-system]
build-backend = "setuptools.build_meta"

requires = [ "setuptools>=80", "setuptools-scm[toml]>=6.2" ]

[project]
name = "fiab-plugin-ecmwf"
description = "Weather Forecast in a Box, ECMWF plugin"
readme = "README.md"
license = "Apache-2.0"
license-files = [ "LICENSE" ]
authors = [
  { name = "European Centre for Medium-Range Weather Forecasts (ECMWF)", email = "software.support@ecmwf.int" },
]
requires-python = ">=3.11"

dynamic = [ "version" ]

dependencies = [
    "fiab-core>=0.0.1,<1.0.0", # ~=0.0
    "earthkit-workflows",
]

optional-dependencies.runtime = [
    "earthkit-data>=0.18.2",
    "earthkit>=0.13.2",
]

[dependency-groups]
dev = [
  "ty==0.0.2",
]

[tool.setuptools_scm]
version_file = "src/fiab_plugin_ecmwf/_version.py"
write_to_template = '''# Do not change! Do not track in version control!
__version__ = "{version}"
'''
local_scheme = "no-local-version"
root = ".."
fallback_version = "0.0.0"
tag_regex = '^[vd](?P<version>\d+(?:\.\d+){0,2}[^\+]*)(?:\+.*)?$'

[tool.ruff]
line-length = 140

lint.ignore = [ "E731" ]