# default config is empty atm
# for all possible keys and values, consult the forecastbox/config.py file for now

# eventually we'll have like a default.singlelaptop.toml and default.server.toml, but not yet
