name: bigtest

# DA BIG TEST
# launches the backend, downloads a model, executes full blown forecast job, ensures success
# not executed regularly, this is too much dakka

on:
  # Trigger the workflow manually
  workflow_dispatch: ~


jobs:
  macos:
    name: macos
    strategy:
      fail-fast: true
      matrix:
        arch_type: [ARM64]
        python_version: ["3.11"] # replace with 3.14 in ~26/01, once all wheels etc available
    runs-on: [self-hosted, macOS, "${{ matrix.arch_type }}"]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - run: |
          set -euo pipefail
          mkdir /tmp/tmpFiabHome # we want a clean env for install
          export FIAB_LOGSTDOUT=yea
          export FIAB_ROOT=/tmp/tmpFiabHome
          bash ./scripts/fiab.sh warmup
          source /tmp/tmpFiabHome/venv/bin/activate
          PYTHONPATH=backend/tests/nonpytest python -m bigtest
